version: "3"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: crm-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-crm_db}
      - PORT=4000
    depends_on:
      - postgres
    volumes:
      - ./apps/api/uploads:/app/uploads
    networks:
      - crm-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: crm-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:4000/api
    depends_on:
      - api
    networks:
      - crm-network

  postgres:
    image: postgres:15-alpine
    container_name: crm-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-crm_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network

volumes:
  postgres_data:
    driver: local

networks:
  crm-network:
    driver: bridge
