version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "npm run build && npm run start"
    restart: always
